[general]
import = ["~/.config/alacritty/os.toml"]

[window]
opacity = 0.85
decorations = "none"

[scrolling]
history = 100000

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "Never"

[colors.primary]
background = "#000000"
foreground = "#dddddd"
