# start up commands
after-login-command = []
after-startup-command = []
start-at-login = true

# normalizations
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# for when accordion mode is enabled
accordion-padding = 20

default-root-container-orientation = 'auto'

# background commands
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# sweets
automatically-unhide-macos-hidden-apps = true

[key-mapping]
  preset = 'qwerty'

[gaps]
  outer.top = 8
  outer.right = 8
  outer.bottom = 8
  outer.left = 8
  inner.horizontal = 8
  inner.vertical = 8

[mode.main.binding]
  cmd-alt-h = []
  cmd-shift-c = ['reload-config', 'mode main']

  # move to service mode
  alt-shift-semicolon = 'mode service'

  # move workspaces to different monitors
  alt-ctrl-shift-h = ['move-workspace-to-monitor left']
  alt-ctrl-shift-l = ['move-workspace-to-monitor right']

  # basic window navigation
  cmd-h = 'focus left'
  cmd-j = 'focus down'
  cmd-k = 'focus up'
  cmd-l = 'focus right'

  # move windows within workspaces
  cmd-shift-h = 'move left'
  cmd-shift-j = 'move down'
  cmd-shift-k = 'move up'
  cmd-shift-l = 'move right'

  # basic workspace navigation
  cmd-1 = ['workspace 1', 'mode main']
  cmd-2 = ['workspace 2', 'mode main']
  cmd-3 = ['workspace 3', 'mode main']
  cmd-4 = ['workspace 4', 'mode main']
  cmd-5 = ['workspace 5', 'mode main']
  cmd-6 = ['workspace 6', 'mode main']
  cmd-7 = ['workspace 7', 'mode main']
  cmd-8 = ['workspace 8', 'mode main']
  cmd-9 = ['workspace 9', 'mode main']
  cmd-0 = ['workspace 10', 'mode main']

  # move windows to workspaces
  cmd-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
  cmd-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
  cmd-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
  cmd-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
  cmd-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
  cmd-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
  cmd-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
  cmd-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
  cmd-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
  cmd-shift-0 = ['move-node-to-workspace 10', 'workspace 10']

  # back and forth between workspaces
  cmd-backtick = 'workspace-back-and-forth'

[mode.service.binding]
  esc = ['mode main']

  j = 'volume down'
  k = 'volume up'
  shift-j = ['volume set 0', 'mode main']
