# --ozone-platform-hint=auto
# --force-dark-mode
# --enable-features=WebUIDarkMode

--enable-features=UseOzonePlatform,WebUIDarkMode,TouchpadOverscrollHistoryNavigation,WebUIDarkMode
--ozone-platform=wayland
--force-dark-mode
