#!/bin/bash

if [[ $EUID -ne 0 ]]; then
    echo "This script requires sudo privileges"
    sudo -v || exit 1
fi

# Keep sudo alive
while true; do
    sudo -n true
    sleep 60
    kill -0 "$$" || exit
done 2>/dev/null &

# Load stripe environment

unset STRIPE_SECRET_KEY

export PASSWORD_STORE_GPG_OPTS="--pinentry=loopback --passphrase 1984@Tsupriyo"

export STRIPE_SECRET_KEY=$(pass show access_tokens/stripe/test/secret)

echo "Stripe Environment loaded"
