#!/usr/bin/env sh

# Terminate already running bar instances
# killall -q waybar

# Wait until the processes have been shut down
# while pgrep -x waybar >/dev/null; do sleep 1; done

WAYBAR_CONFIG="$HOME/.config/hypr/components/waybar/config.jsonc"
WAYBAR_STYLE="$HOME/.config/hypr/components/waybar/style.css"

# CONFIG_FILES="$WAYBAR_CONFIG $WAYBAR_STYLE"

# trap "killall waybar" EXIT

waybar -c $WAYBAR_CONFIG -s $WAYBAR_STYLE &
# while true; do
#   pkill -SIGUSR1 waybar
#   inotifywait -e create,modify $CONFIG_FILES
#   killall waybar
# done
