#!/bin/bash

# Path to store the last IPv6 address
IP_FILE="/home/roysupriyo10/personal/cloudflare/last_ip.txt"

# Interface to check the IPv6 address, e.g., eth0, ens33
IFACE="wlo1"

# Script to run if the IPv6 address has changed
SCRIPT="/home/roysupriyo10/personal/cloudflare/update-aaaa"

# Get the current global IPv6 address of the interface
CURRENT_IP=$(ip -6 addr show $IFACE | grep "inet6" | grep "global" | awk '{print $2}' | sed 's/\/.*$//')

# Check if the IP file exists and read the last IP address
if [ -f "$IP_FILE" ]; then
    LAST_IP=$(cat "$IP_FILE")
else
    LAST_IP=""
fi

# Compare the current IP with the last known IP
if [ "$CURRENT_IP" != "$LAST_IP" ]; then
    echo "IPv6 address has changed to $CURRENT_IP"
    # Save the new IP address to the file
    echo "$CURRENT_IP" > "$IP_FILE"
    # Execute the script
    if [ -f "$SCRIPT" ]; then
        bash "$SCRIPT"
    else
        echo "Script not found: $SCRIPT"
    fi
else
    echo "IPv6 address has not changed."
fi
