#!/bin/bash

# Cloudflare zone is the zone which holds the record
zone=supriyo.cloud
# dnsrecord is the A record which will be updated
dnsrecord=bael.supriyo.cloud

## Cloudflare authentication details
cloudflare_auth_email=roysupriyo10@gmail.com
cloudflare_auth_key=$(pass show apitokens/cloudflare)


# Get the current external IPv6 address
ip=$(ip -6 addr show scope global | awk '/inet6/ {gsub(/\/64/, "", $2); print $2; exit}')

echo "Current IP is $ip"

echo "Current pointed IP is $(getent hosts $dnsrecord | awk '{gsub(/ .*/, ""); print}')"

# echo $(ip -6 addr show scope global | awk '/inet6/ {gsub(/\/64/, "", $2); print $2; exit}')
#
# echo 'printing the dns record'

# echo $(getent hosts $dnsrecord | awk '{gsub(/ .*/, ""); print}')
if getent hosts $dnsrecord | awk '{gsub(/ .*/, ""); print}' | grep $ip; then
  echo "$dnsrecord is currently set to $ip; no changes needed"
  exit
fi

# if here, the dns record needs updating
# get the zone id for the requested zone
zoneid=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=$zone&status=active" \
  -H "X-Auth-Email: $cloudflare_auth_email" \
  -H "X-Auth-Key: $cloudflare_auth_key" \
  -H "Content-Type: application/json" | jq -r '{"result"}[] | .[0] | .id')

echo "Zoneid for $zone is $zoneid"

# get the dns record id
dnsrecordid=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zoneid/dns_records?type=AAAA&name=$dnsrecord" \
  -H "X-Auth-Email: $cloudflare_auth_email" \
  -H "X-Auth-Key: $cloudflare_auth_key" \
  -H "Content-Type: application/json" | jq -r '{"result"}[] | .[0] | .id')

echo "DNSrecordid for $dnsrecord is $dnsrecordid"

# update the record
curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$zoneid/dns_records/$dnsrecordid" \
  -H "X-Auth-Email: $cloudflare_auth_email" \
  -H "X-Auth-Key: $cloudflare_auth_key" \
  -H "Content-Type: application/json" \
  --data "{\"type\":\"AAAA\",\"name\":\"$dnsrecord\",\"content\":\"$ip\",\"ttl\":1,\"proxied\":false}" | jq


